{
	"version": 1647547525,
	"fileList": [
		"data.js",
		"game.html",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite1-sheet0.png",
		"images/rectangle-sheet0.png",
		"images/group-sheet0.png",
		"images/sprite-sheet0.png",
		"images/group2-sheet0.png",
		"images/hоmepage-sheet0.png",
		"images/hоmepage-sheet1.png",
		"images/other-sheet0.png",
		"images/other-sheet1.png",
		"images/rating-sheet0.png",
		"images/rating-sheet1.png",
		"images/otherscreen-sheet0.png",
		"images/start3buttonone-sheet0.png",
		"images/start3buttonotwo-sheet0.png",
		"images/group3-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/authtext-sheet0.png",
		"images/authtext2-sheet0.png",
		"images/group4-sheet0.png",
		"images/name-sheet0.png",
		"images/ooo-sheet0.png",
		"images/zao-sheet0.png",
		"images/oao-sheet0.png",
		"images/group5-sheet0.png",
		"images/authbutton-sheet0.png",
		"images/auth2text-sheet0.png",
		"images/group6-sheet0.png",
		"images/main1dock-sheet0.png",
		"images/d-sheet0.png",
		"images/d3-sheet0.png",
		"images/d3-sheet1.png",
		"images/d4-sheet0.png",
		"images/d4-sheet1.png",
		"images/d5-sheet0.png",
		"images/t1op-sheet0.png",
		"images/t2op-sheet0.png",
		"images/t3op-sheet0.png",
		"images/t4op-sheet0.png",
		"images/t5op-sheet0.png",
		"images/t6op-sheet0.png",
		"images/t7op-sheet0.png",
		"images/t8op-sheet0.png",
		"images/tvvvop-sheet0.png",
		"images/d3text-sheet0.png",
		"images/d3sp-sheet0.png",
		"images/d3sp2-sheet0.png",
		"images/d3sp3-sheet0.png",
		"images/d3sp3-sheet1.png",
		"images/group8-sheet0.png",
		"images/group9-sheet0.png",
		"images/rectangle2-sheet0.png",
		"images/rectangle3-sheet0.png",
		"images/main1icon-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ubuntu medium.css",
		"ubuntu medium.eot",
		"ubuntu medium.html",
		"ubuntu medium.svg",
		"ubuntu medium.woff",
		"ubuntu medium.woff2",
		"ubuntu bold.css",
		"ubuntu bold.eot",
		"ubuntu bold.html",
		"ubuntu bold.svg",
		"ubuntu bold.woff",
		"ubuntu bold.woff2",
		"firebase.js"
	]
}