{
	"version": 1647506733,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/login-sheet0.png",
		"images/ca4-sheet0.png",
		"images/rectangle5-sheet0.png",
		"images/barcode-sheet0.png",
		"images/rectangle6-sheet0.png",
		"images/rectangle7-sheet0.png",
		"images/ЗАО-sheet0.png",
		"images/ЗАО2-sheet0.png",
		"images/ООО-sheet0.png",
		"images/ca5-sheet0.png",
		"images/ca7-sheet0.png",
		"images/ca6-sheet0.png",
		"images/ca6-sheet1.png",
		"images/withoutinternet-sheet0.png",
		"images/ellipse-sheet0.png",
		"images/rectangle-sheet0.png",
		"images/rectangle2-sheet0.png",
		"images/rectangle3-sheet0.png",
		"images/sprite-sheet0.png",
		"images/rectangle4-sheet0.png",
		"images/ca1-sheet0.png",
		"images/ca3-sheet0.png",
		"images/arrow-sheet0.png",
		"images/cam-sheet0.png",
		"images/ca10-sheet0.png",
		"images/ca13-sheet0.png",
		"images/ca16-sheet0.png",
		"images/group-sheet0.png",
		"images/ca12-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/rectangle8-sheet0.png",
		"images/rectangle9-sheet0.png",
		"images/dok_button5-sheet0.png",
		"images/dok_button5-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/rectangle10-sheet0.png",
		"images/ca18-sheet0.png",
		"images/ca19-sheet0.png",
		"images/dockstartv-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/ca9-sheet0.png",
		"images/ca17-sheet0.png",
		"images/sprited-sheet0.png",
		"images/testcam-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/group11-sheet0.png",
		"images/group22-sheet0.png",
		"images/group33-sheet0.png",
		"images/group44-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ubuntu bold.css",
		"ubuntu bold.eot",
		"ubuntu bold.html",
		"ubuntu bold.svg",
		"ubuntu bold.woff",
		"ubuntu bold.woff2",
		"ubuntu bold italic.css",
		"ubuntu bold italic.eot",
		"ubuntu bold italic.html",
		"ubuntu bold italic.svg",
		"ubuntu bold italic.woff",
		"ubuntu bold italic.woff2",
		"ubuntu italic.css",
		"ubuntu italic.eot",
		"ubuntu italic.html",
		"ubuntu italic.svg",
		"ubuntu italic.woff",
		"ubuntu italic.woff2",
		"ubuntu light.css",
		"ubuntu light.eot",
		"ubuntu light.html",
		"ubuntu light.svg",
		"ubuntu light.woff",
		"ubuntu light.woff2",
		"ubuntu light italic.css",
		"ubuntu light italic.eot",
		"ubuntu light italic.html",
		"ubuntu light italic.svg",
		"ubuntu light italic.woff",
		"ubuntu light italic.woff2",
		"ubuntu medium.css",
		"ubuntu medium.eot",
		"ubuntu medium.html",
		"ubuntu medium.svg",
		"ubuntu medium.woff",
		"ubuntu medium.woff2",
		"ubuntu medium italic.css",
		"ubuntu medium italic.eot",
		"ubuntu medium italic.html",
		"ubuntu medium italic.svg",
		"ubuntu medium italic.woff",
		"ubuntu medium italic.woff2",
		"ubuntu regular.css",
		"ubuntu regular.eot",
		"ubuntu regular.html",
		"ubuntu regular.svg",
		"ubuntu regular.woff",
		"ubuntu regular.woff2",
		"firebase.js",
		"chance.min.js"
	]
}